language: go

before_install:
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/schollz/snaptext/...
  
go:
  - "1.3"
  - "1.4"
  - "1.5"
  - "1.6"
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "tip"
